steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - readfeed-create-bookmark
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python312
options:
  logging: CLOUD_LOGGING_ONLY
