steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - readfeed-create-bookmark
  - --entry-point=create_bookmark
  - --region=us-central1
  - --source=./functions/create_bookmark
  - --trigger-http
  - --runtime=python312
  - --no-allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
